default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: pjud
  password: cascais
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: pet_api_development

test:
  <<: *default
  database: pet_api_test

production:
  <<: *default
  database: pet_api_production
  username: pjud
  password: cascais